/* tslint:disable */
/* eslint-disable */
/**
 * hello/hello.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HelloReply
 */
export interface HelloReply {
    /**
     * 
     * @type {string}
     * @memberof HelloReply
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof HelloReply
     */
    name?: string;
}

/**
 * Check if a given object implements the HelloReply interface.
 */
export function instanceOfHelloReply(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HelloReplyFromJSON(json: any): HelloReply {
    return HelloReplyFromJSONTyped(json, false);
}

export function HelloReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloReply {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function HelloReplyToJSON(value?: HelloReply | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'name': value.name,
    };
}

